com.digitald4.iis.router = function($routeProvider) {
	$routeProvider
		.when('/dashboard', {
			templateUrl: 'js/html/dashboard.html'
		}).when('/profile', {
			controller: 'ProfileCtrl',
			controllerAs: 'profileCtrl',
			templateUrl: 'js/html/profile.html'
		}).when('/patients', {
			templateUrl: 'js/html/patients.html'
		}).when('/patient', {
			controller: 'PatientCtrl',
			controllerAs: 'patientCtrl',
			templateUrl: 'js/html/patient.html'
		}).when('/pendass', {
			templateUrl: 'js/html/pending_ass.html'
		}).when('/intake', {
			controller: 'IntakeCtrl',
			controllerAs: 'intakeCtrl',
			templateUrl: 'js/html/intake.html'
		}).when('/pintake', {
			templateUrl: 'js/html/pending_intake.html'
		}).when('/users', {
			templateUrl: 'js/html/users.html'
		}).when('/user', {
			controller: 'UserCtrl',
			controllerAs: 'userCtrl',
			templateUrl: 'js/html/user.html'
		}).when('/useradd', {
			controller: 'UserAddCtrl',
			controllerAs: 'userAddCtrl',
			templateUrl: 'js/html/user_add.html'
		}).when('/billable', {
			templateUrl: 'js/html/billable.html'
		}).when('/payable', {
			templateUrl: 'js/html/payables.html'
		}).when('/unpaid_invoices', {
			templateUrl: 'js/html/unpaid_invoices.html'
		}).when('/paid_invoices', {
			templateUrl: 'js/html/paid_invoices.html'
		}).when('/pay_history', {
			templateUrl: 'js/html/pay_history.html'
		}).when('/vendors', {
			templateUrl: 'js/html/vendors.html'
		}).when('/vendor/:vendorId', {
			controller: 'VendorCtrl',
			controllerAs: 'vendorCtrl',
			templateUrl: 'js/html/vendor.html'
		}).when('/vendor_add', {
			controller: 'VendorAddCtrl',
			controllerAs: 'vendorAddCtrl',
			templateUrl: 'js/html/vendor_add.html'
		}).when('/nurses', {
			templateUrl: 'js/html/nurses.html'
		}).when('/nurse', {
			controller: 'NurseCtrl',
			controllerAs: 'nurseCtrl',
			templateUrl: 'js/html/nurse.html'
		}).when('/nurse_add', {
			controller: 'NurseAddCtrl',
			controllerAs: 'nurseAddCtrl',
			templateUrl: 'js/html/nurse_add.html'
		}).when('/license_alert', {
			templateUrl: 'js/html/license_alert.html'
		}).when('/uncomfirmed', {
			templateUrl: 'js/html/uncomfirmed.html'
		}).when('/reports', {
			templateUrl: 'js/html/reports.html'
		}).otherwise({ redirectTo: '/dashboard'});
};
