package com.digitald4.util;
import com.digitald4.pm.servlet.AccountServlet;
import com.digitald4.pm.servlet.AddClientConfirmServlet;
import com.digitald4.pm.servlet.AddClientServlet;
import com.digitald4.pm.servlet.AdminSearchServlet;
import com.digitald4.pm.servlet.AdminServlet;
import com.digitald4.pm.servlet.AgentInfoAjax;
import com.digitald4.pm.servlet.AssignExaminerConfirmServlet;
import com.digitald4.pm.servlet.AssignExaminerServlet;
import com.digitald4.pm.servlet.ClientExamServlet;
import com.digitald4.pm.servlet.ClientServlet;
import com.digitald4.pm.servlet.ContactServlet;
import com.digitald4.pm.servlet.DeniedServlet;
import com.digitald4.pm.servlet.FaqServlet;
import com.digitald4.pm.servlet.HomeServlet;
import com.digitald4.pm.servlet.IframeServlet;
import com.digitald4.pm.servlet.LinkServlet;
import com.digitald4.pm.servlet.LoginServlet;
import com.digitald4.pm.servlet.LogoutServlet;
import com.digitald4.pm.servlet.NewsServlet;
import com.digitald4.pm.servlet.PDFRequisitionServlet;
import com.digitald4.pm.servlet.ParentServlet;
import com.digitald4.pm.servlet.SearchServlet;
import com.digitald4.pm.servlet.TestimonialServlet;
import com.digitald4.pm.servlet.UploadServlet;
@SuppressWarnings("unused")
public class CompileMe{
	private AccountServlet account;
	private AddClientConfirmServlet addClientConfirm;
	private AddClientServlet addClient;
	private AdminSearchServlet adminSearch;
	private AdminServlet admin;
	private AgentInfoAjax ajax;
	private AssignExaminerConfirmServlet assignConfirm;
	private AssignExaminerServlet assign;
	private ContactServlet contact;
	private ClientServlet client;
	private ClientExamServlet ce;
	private DeniedServlet denied;
	private FaqServlet faq;
	private HomeServlet home;
	private HighlightTerm hi;
	private IframeServlet iframe;
	//private InsuranceServlet ins;
	private LinkServlet link;
	private LoginServlet login;
	private LogoutServlet logout;
	private NewsServlet news;
	private ObjectUpdateServlet ous;
	private ParentServlet parent;
	private PDFRequisitionServlet requisition;
	private SearchServlet search;
	private TestimonialServlet testimonial;
	private UploadServlet upload;
}