CREATE TABLE general_data(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GROUP_ID INT,
	IN_GROUP_ID INT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	RANK DECIMAL,
	ACTIVE BOOLEAN DEFAULT 1,
	DESCRIPTION VARCHAR(256),
	DATA VARCHAR(128)
);

CREATE TABLE user(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TYPE_ID INT NOT NULL,
	EMAIL VARCHAR(64) NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	DISABLED BOOLEAN,
	READ_ONLY BOOLEAN,
	PASSWORD VARCHAR(128),
	NOTES VARCHAR(256),
	LAST_LOGIN DATETIME
);

CREATE TABLE nurse(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REG_DATE DATE,
	ACTIVE BOOLEAN DEFAULT true,
	ADDRESS VARCHAR(50) NOT NULL,
	LATITUDE DECIMAL,
	LONGITUDE DECIMAL,
	PHONE_NUMBER VARCHAR(20),
	REFERRAL_SOURCE VARCHAR(100),
	PAY_RATE DECIMAL NOT NULL,
	PAY_RATE_2HR_SOC DECIMAL,
	PAY_RATE_2HR_ROC DECIMAL,
	MILEAGE_RATE DECIMAL
);

CREATE TABLE license(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NURSE_ID INT NOT NULL,
	LIC_TYPE_ID INT NOT NULL,
	NUMBER VARCHAR(32),
	VALID_DATE DATE,
	EXPIRATION_DATE DATE
);

CREATE TABLE patient(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REFERRAL_DATE DATE,
	REFERRAL_SOURCE_ID INT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	MR_NUM VARCHAR(16),
	DIANOSIS_ID INT,
	THERAPY_TYPE_ID INT,
	I_V_ACCESS_ID INT,
	START_OF_CARE BOOLEAN,
	START_OF_CARE_DATE DATE,
	SERVICE_ADDRESS VARCHAR(50),
	LATITUDE DECIMAL,
	LONGITUDE DECIMAL,
	BILLING_ID INT,
	RX VARCHAR(128),
	EST_LAST_DAY_OF_SERVICE DATE,
	LABS BOOLEAN,
	LABS_FREQUENCY VARCHAR(64),
	FIRST_RECERT_DUE DATE,
	D_C_DATE VARCHAR(64),
	INFO_IN_S_O_S BOOLEAN,
	SCHEDULING_PREFERENCE VARCHAR(64),
	REFERRAL_NOTE VARCHAR(1024),
	REFERRAL_RESOLUTION_ID INT,
	REFERRAL_RESOLUTION_DATE DATE,
	REFERRAL_RESOLUTION_NOTE VARCHAR(512),
	VENDOR_CONFIRMATION_DATE DATE,
	NURSE_CONFIRMATION_DATE DATE,
	PATIENT_CONFIRMATION_DATE DATE,
	MEDS_DELIVERY_DATE DATE,
	MEDS_CONFIRMATION_DATE DATE,
	ACTIVE BOOLEAN DEFAULT 1,
	DESCRIPTION VARCHAR(256)
);

CREATE TABLE appointment(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PATIENT_ID INT NOT NULL,
	NURSE_ID INT,
	START DATETIME NOT NULL,
	END DATETIME NOT NULL,
	CANCELLED BOOLEAN,
	TIME_IN DATETIME,
	TIME_OUT DATETIME,
	MILEAGE SMALLINT,
	ASSESSMENT_COMPLETE BOOLEAN,
	PAYMENT_DATE DATE
);

CREATE TABLE assessment_entry(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	APPOINTMENT_ID INT NOT NULL,
	ASSESSMENT_ID INT NOT NULL,
	VALUE_ID INT,
	VALUE_STR VARCHAR(64),
	ACK BOOLEAN
);
