package com.digitald4.util;
import com.digitald4.pm.servlet.*;
public class CompileMe{
	private AccountServlet account;
	private AddClientConfirmServlet addClientConfirm;
	private AddClientServlet addClient;
	private AdminSearchServlet adminSearch;
	private AdminServlet admin;
	private AgentInfoAjax ajax;
	private AssignExaminerConfirmServlet assignConfirm;
	private AssignExaminerServlet assign;
	private ContactServlet contact;
	private ClientServlet client;
	private ClientExamServlet ce;
	private DeniedServlet denied;
	private FaqServlet faq;
	private HomeServlet home;
	private HighlightTerm hi;
	private IframeServlet iframe;
	//private InsuranceServlet ins;
	private LinkServlet link;
	private LoginServlet login;
	private LogoutServlet logout;
	private NewsServlet news;
	private ObjectUpdateServlet ous;
	private ParentServlet parent;
	private PDFRequisitionServlet requisition;
	private SearchServlet search;
	private TestimonialServlet testimonial;
	private UploadServlet upload;
}